version: '3'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    environment:
      - DB_SQLITE_FILE=/data/database.sqlite  # Use SQLite database
      - PORT=8080
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
